name: Build backend image

on:
  push:
    branches: ["main", "ci_test"]

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B compile -DskipTests --file backend/pom.xml

      - name: Create package
        run: mvn -B package -DskipTests --file backend/pom.xml

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          - username: ${{ secrets.DOCKERHUB_USERNAME }}
          - password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: adrianpanek/notices-board-backend:latest

