name: Build Frontend

on:
  workflow_run:
    workflows: [Build Backend]
    types:
      - completed

jobs:
  nodejs:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-verison: 20
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install packages
        run: npm ci

      - name: Build app
        run: npm run build

  docker:
    needs: nodejs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: adrianpanek/notices-board-frontend:latest